# Generated by Django 5.2.13 on 2026-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='categoria',
        ),
        migrations.AddField(
            model_name='plano',
            name='categorias',
            field=models.ManyToManyField(related_name='planos', to='gestao.categoria'),
        ),
    ]
