# Generated by Django 5.2.13 on 2026-04-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_plano_categoria_plano_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='is_matrix',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='parent_escola',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_ESCOLA', 'Admin Escola'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], max_length=20),
        ),
    ]
