# Generated by Django 5.2.13 on 2026-04-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_aulaoverride_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.escola'),
        ),
        migrations.AddField(
            model_name='plano',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.escola'),
        ),
    ]
