# Generated by Django 5.2.13 on 2026-04-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_pacote_escola_plano_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='nome',
            field=models.CharField(default='Nova Aula', max_length=100),
        ),
    ]
