# Generated by Django 5.2.13 on 2026-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_aula_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
