# Generated by Django 5.2.13 on 2026-05-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_despesaescola_pagamentoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaoverride',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aulaoverride',
            name='professor_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_substituidas', to='gestao.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='tipo_salario',
            field=models.CharField(choices=[('FIXO', 'Fixo Mensal'), ('HORA', 'Por Hora/Aula')], default='FIXO', max_length=10),
        ),
        migrations.AddField(
            model_name='professor',
            name='valor_salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aulaoverride',
            name='nova_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aulaoverride',
            name='novo_horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
