# Generated by Django 5.2.12 on 2026-05-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_aluno_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='dia_pagamento',
            field=models.IntegerField(default=5),
        ),
    ]
